services:
  - type: web
    name: pos-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://glowing-scone-b83e4c.netlify.app
    healthCheckPath: /api/health