name: Build Windows Electron App (Packager)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'main.js'
      - 'package.json'

jobs:
  build-windows-packager:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        
    - name: Install root dependencies
      run: pnpm install
      
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm install
        
    - name: Install backend dependencies
      run: |
        cd backend
        npm install --production --no-package-lock
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
        
    - name: Package Windows app with electron-packager
      run: pnpm run package:win
      
    - name: Create zip archive
      run: |
        cd dist/win
        $folderName = Get-ChildItem -Directory | Select-Object -First 1 -ExpandProperty Name
        Compress-Archive -Path $folderName -DestinationPath "sophon-windows-portable.zip"
        
    - name: Upload Windows packaged artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-packaged-build
        path: |
          dist/win/*.zip
          dist/win/*/
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/win/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}